// Sample Data
const sampleProducts = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    price: 2999,
    originalPrice: 4999,
    image: "https://images.pexels.com/photos/3825517/pexels-photo-3825517.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.5,
    reviews: 128,
    description: "High-quality wireless headphones with active noise cancellation, 30-hour battery life, and premium sound quality. Perfect for music lovers and professionals.",
    inStock: true,
    discount: 40,
    brand: "SoundMax",
    colors: ["Black", "Silver", "Blue"],
    features: ["Noise Cancellation", "Bluetooth 5.0", "30hr Battery", "Fast Charging"],
  },
  {
    id: 2,
    name: "Smart Watch Series 5",
    price: 12999,
    originalPrice: 15999,
    image: "https://images.pexels.com/photos/437037/pexels-photo-437037.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.8,
    reviews: 256,
    description: "Latest smartwatch with advanced health tracking, heart rate monitor, GPS, and water resistance up to 50m. Stay connected and healthy.",
    inStock: true,
    discount: 19,
    brand: "TechWatch",
    colors: ["Black", "Silver", "Gold", "Rose Gold"],
    features: ["Heart Rate Monitor", "GPS", "Water Resistant", "Sleep Tracking"],
  },
  {
    id: 3,
    name: "Professional DSLR Camera",
    price: 45999,
    originalPrice: 52999,
    image: "https://images.pexels.com/photos/90946/pexels-photo-90946.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.7,
    reviews: 89,
    description: "Professional DSLR camera with 24MP sensor, 4K video recording, and advanced autofocus system. Includes 18-55mm lens kit.",
    inStock: false,
    discount: 13,
    brand: "CanonX",
    colors: ["Black"],
    features: ["24MP Sensor", "4K Video", "WiFi", "Dual Card Slots"],
  },
  {
    id: 4,
    name: "Laptop Backpack Pro",
    price: 1499,
    originalPrice: 2499,
    image: "https://images.pexels.com/photos/2905238/pexels-photo-2905238.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Fashion",
    rating: 4.3,
    reviews: 445,
    description: "Durable water-resistant laptop backpack with USB charging port, multiple compartments, and anti-theft design. Fits up to 15.6-inch laptops.",
    inStock: true,
    discount: 40,
    brand: "TravelGear",
    colors: ["Black", "Grey", "Navy Blue"],
    features: ["USB Port", "Water Resistant", "Anti-theft", "Laptop Compartment"],
  },
  {
    id: 5,
    name: "Bluetooth Speaker Pro",
    price: 2499,
    originalPrice: 3999,
    image: "https://images.pexels.com/photos/8000618/pexels-photo-8000618.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.6,
    reviews: 180,
    description: "Portable waterproof Bluetooth speaker with 360° surround sound, deep bass, and 20-hour battery life. Perfect for outdoor adventures.",
    inStock: true,
    discount: 38,
    brand: "BassBoost",
    colors: ["Black", "Red", "Blue"],
    features: ["Waterproof IPX7", "20hr Battery", "360° Sound", "USB-C Charging"],
  },
  {
    id: 6,
    name: "Running Shoes Elite",
    price: 3499,
    originalPrice: 5999,
    image: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Fashion",
    rating: 4.7,
    reviews: 342,
    description: "Lightweight running shoes with cushioned sole, breathable mesh upper, and enhanced grip. Designed for maximum comfort and performance.",
    inStock: true,
    discount: 42,
    brand: "RunFast",
    colors: ["White", "Black", "Red", "Blue"],
    features: ["Breathable Mesh", "Cushioned Sole", "Anti-slip", "Lightweight"],
  },
  {
    id: 7,
    name: "Mechanical Gaming Keyboard",
    price: 4999,
    originalPrice: 7999,
    image: "https://images.pexels.com/photos/2582937/pexels-photo-2582937.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.8,
    reviews: 523,
    description: "RGB mechanical gaming keyboard with customizable backlighting, programmable keys, and ultra-responsive switches for competitive gaming.",
    inStock: true,
    discount: 38,
    brand: "GamePro",
    colors: ["Black"],
    features: ["RGB Backlight", "Mechanical Keys", "Programmable", "Anti-ghosting"],
  },
  {
    id: 8,
    name: "Stainless Steel Water Bottle",
    price: 799,
    originalPrice: 1299,
    image: "https://images.pexels.com/photos/3735218/pexels-photo-3735218.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Sports",
    rating: 4.5,
    reviews: 678,
    description: "Insulated stainless steel water bottle keeps drinks cold for 24 hours or hot for 12 hours. BPA-free and leak-proof design.",
    inStock: true,
    discount: 38,
    brand: "HydroLife",
    colors: ["Silver", "Black", "Blue", "Pink", "Green"],
    features: ["Insulated", "BPA Free", "Leak Proof", "1 Liter Capacity"],
  },
  {
    id: 9,
    name: "Yoga Mat Premium",
    price: 1299,
    originalPrice: 2499,
    image: "https://images.pexels.com/photos/4498362/pexels-photo-4498362.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Sports",
    rating: 4.6,
    reviews: 234,
    description: "Extra-thick non-slip yoga mat with alignment markers. Made from eco-friendly TPE material with excellent cushioning and grip.",
    inStock: true,
    discount: 48,
    brand: "ZenFlow",
    colors: ["Purple", "Blue", "Pink", "Green"],
    features: ["Non-slip", "Eco-friendly", "6mm Thick", "Carrying Strap"],
  },
  {
    id: 10,
    name: "Coffee Maker Deluxe",
    price: 5999,
    originalPrice: 8999,
    image: "https://images.pexels.com/photos/324028/pexels-photo-324028.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Home",
    rating: 4.4,
    reviews: 156,
    description: "Programmable coffee maker with thermal carafe, brew strength control, and auto shut-off. Makes up to 12 cups of perfect coffee.",
    inStock: true,
    discount: 33,
    brand: "BrewMaster",
    colors: ["Black", "Silver"],
    features: ["Programmable", "Thermal Carafe", "12 Cup Capacity", "Auto Shut-off"],
  },
  {
    id: 11,
    name: "Wireless Gaming Mouse",
    price: 2799,
    originalPrice: 4499,
    image: "https://images.pexels.com/photos/2115256/pexels-photo-2115256.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.7,
    reviews: 445,
    description: "Ergonomic wireless gaming mouse with 16000 DPI sensor, RGB lighting, and programmable buttons. Ultra-fast response time for competitive gaming.",
    inStock: true,
    discount: 38,
    brand: "GamePro",
    colors: ["Black"],
    features: ["16000 DPI", "RGB Lighting", "Wireless", "6 Programmable Buttons"],
  },
  {
    id: 12,
    name: "Portable Phone Charger 20000mAh",
    price: 1999,
    originalPrice: 3499,
    image: "https://images.pexels.com/photos/4195325/pexels-photo-4195325.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.5,
    reviews: 892,
    description: "High-capacity portable power bank with fast charging technology. Charges multiple devices simultaneously with LED display showing battery level.",
    inStock: true,
    discount: 43,
    brand: "PowerMax",
    colors: ["Black", "White"],
    features: ["20000mAh", "Fast Charging", "LED Display", "Dual USB Ports"],
  },
  {
    id: 13,
    name: "Fitness Tracker Band",
    price: 2299,
    originalPrice: 3999,
    image: "https://images.pexels.com/photos/4498155/pexels-photo-4498155.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Sports",
    rating: 4.3,
    reviews: 567,
    description: "Activity tracker with heart rate monitor, sleep tracking, and waterproof design. Syncs with smartphone for detailed health insights.",
    inStock: true,
    discount: 43,
    brand: "FitLife",
    colors: ["Black", "Blue", "Pink"],
    features: ["Heart Rate Monitor", "Sleep Tracking", "Waterproof", "7 Day Battery"],
  },
  {
    id: 14,
    name: "LED Desk Lamp",
    price: 1799,
    originalPrice: 2999,
    image: "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Home",
    rating: 4.6,
    reviews: 234,
    description: "Adjustable LED desk lamp with touch control, multiple brightness levels, and USB charging port. Eye-caring technology reduces eye strain.",
    inStock: true,
    discount: 40,
    brand: "LightPro",
    colors: ["White", "Black", "Silver"],
    features: ["Touch Control", "USB Port", "Adjustable Arm", "Eye-caring LED"],
  },
  {
    id: 15,
    name: "Wireless Earbuds Pro",
    price: 3999,
    originalPrice: 6999,
    image: "https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg?auto=compress&cs=tinysrgb&w=500",
    category: "Electronics",
    rating: 4.7,
    reviews: 1023,
    description: "True wireless earbuds with active noise cancellation, premium sound quality, and 24-hour battery life with charging case.",
    inStock: true,
    discount: 43,
    brand: "SoundMax",
    colors: ["White", "Black"],
    features: ["ANC", "Touch Control", "24hr Battery", "IPX4 Water Resistant"],
  },
];

const sampleReviews = [
  {
    id: 1,
    userName: "Rahul Kumar",
    rating: 5,
    date: "2 days ago",
    comment: "Excellent product! Really loved the quality and fast delivery.",
    helpful: 24,
  },
  {
    id: 2,
    userName: "Priya Singh",
    rating: 4,
    date: "1 week ago",
    comment: "Good product but packaging could be better. Overall satisfied!",
    helpful: 12,
  },
  {
    id: 3,
    userName: "Amit Patel",
    rating: 5,
    date: "2 weeks ago",
    comment: "Amazing value for money. Highly recommended!",
    helpful: 38,
  },
];

const sampleOrders = [
  {
    id: "ORD123456",
    date: "2024-01-04",
    total: 15998,
    status: "delivered",
    address: "123 Main St, Tiruchirappalli, India",
    items: 2,
    trackingSteps: [
      { status: "ordered", label: "Order Placed", date: "Jan 04, 10:30 AM", completed: true },
      { status: "confirmed", label: "Order Confirmed", date: "Jan 04, 11:00 AM", completed: true },
      { status: "shipped", label: "Shipped", date: "Jan 05, 09:00 AM", completed: true },
      { status: "out_for_delivery", label: "Out for Delivery", date: "Jan 06, 08:00 AM", completed: true },
      { status: "delivered", label: "Delivered", date: "Jan 06, 02:30 PM", completed: true },
    ],
    products: [
      { ...sampleProducts[0], quantity: 1 },
      { ...sampleProducts[1], quantity: 1 },
    ],
  },
  {
    id: "ORD123455",
    date: "2024-01-02",
    total: 2999,
    status: "shipped",
    address: "45 MG Road, Bengaluru, India",
    items: 1,
    trackingSteps: [
      { status: "ordered", label: "Order Placed", date: "Jan 02, 03:00 PM", completed: true },
      { status: "confirmed", label: "Order Confirmed", date: "Jan 02, 03:30 PM", completed: true },
      { status: "shipped", label: "Shipped", date: "Jan 03, 10:00 AM", completed: true },
      { status: "out_for_delivery", label: "Out for Delivery", date: "Expected Jan 07", completed: false },
      { status: "delivered", label: "Delivered", date: "Pending", completed: false },
    ],
    products: [{ ...sampleProducts[3], quantity: 1 }],
  },
  {
    id: "ORD123457",
    date: "2024-02-10",
    total: 18498,
    status: "out_for_delivery",
    address: "78 Nehru Street, Chennai, India",
    items: 2,
    trackingSteps: [
      { status: "ordered", label: "Order Placed", date: "Feb 10, 09:00 AM", completed: true },
      { status: "confirmed", label: "Order Confirmed", date: "Feb 10, 10:00 AM", completed: true },
      { status: "shipped", label: "Shipped", date: "Feb 11, 11:00 AM", completed: true },
      { status: "out_for_delivery", label: "Out for Delivery", date: "Feb 12, 08:00 AM", completed: false },
      { status: "delivered", label: "Delivered", date: "Pending", completed: false },
    ],
    products: [
      { ...sampleProducts[1], quantity: 1 },
      { ...sampleProducts[4], quantity: 1 },
    ],
  },
  {
    id: "ORD123458",
    date: "2024-03-01",
    total: 45999,
    status: "shipped",
    address: "22 Park Avenue, Mumbai, India",
    items: 1,
    trackingSteps: [
      { status: "ordered", label: "Order Placed", date: "Mar 01, 02:00 PM", completed: true },
      { status: "confirmed", label: "Order Confirmed", date: "Mar 01, 02:30 PM", completed: true },
      { status: "shipped", label: "Shipped", date: "Mar 02, 09:00 AM", completed: true },
      { status: "out_for_delivery", label: "Out for Delivery", date: "Expected Mar 05", completed: false },
      { status: "delivered", label: "Delivered", date: "Pending", completed: false },
    ],
    products: [{ ...sampleProducts[2], quantity: 1 }],
  },
  {
    id: "ORD123459",
    date: "2024-03-05",
    total: 3998,
    status: "delivered",
    address: "55 MG Road, Pune, India",
    items: 2,
    trackingSteps: [
      { status: "ordered", label: "Order Placed", date: "Mar 05, 01:00 PM", completed: true },
      { status: "confirmed", label: "Order Confirmed", date: "Mar 05, 01:30 PM", completed: true },
      { status: "shipped", label: "Shipped", date: "Mar 06, 10:00 AM", completed: true },
      { status: "out_for_delivery", label: "Out for Delivery", date: "Mar 07, 08:00 AM", completed: true },
      { status: "delivered", label: "Delivered", date: "Mar 07, 03:00 PM", completed: true },
    ],
    products: [
      { ...sampleProducts[4], quantity: 2 },
    ],
  },
];

export { sampleProducts, sampleReviews, sampleOrders };
